<?php
	define('TELEGRAM_BOT', 'QraAdmin_Bot');	// Username of the bot (Generated on @BotFather)
	define('TELEGRAM_TOKEN', '5929784590:AAFmruOwvR6RUwTF4CjBCK3tp4EYqgGJV_g'); // Token of the bot (Generated by @BotFather)

	//Data validation function
	function checkTelegramAuthorization($auth_data) {
		$check_hash = $auth_data['hash'];
		unset($auth_data['hash']);
		$data_check_arr = [];
		foreach ($auth_data as $key => $value) {
			  $data_check_arr[] = $key . '=' . $value;
		}
		sort($data_check_arr);
		$data_check_string = implode("\n", $data_check_arr);
		$secret_key = hash('sha256', TELEGRAM_TOKEN, true);

		$hash = hash_hmac('sha256', $data_check_string, $secret_key);
		if (strcmp($hash, $check_hash) !== 0) {
			throw new Exception('Data is NOT from Telegram');
		}
		if ((time() - $auth_data['auth_date']) > 86400) {
			throw new Exception('Data is outdated');
		}
		return $auth_data;
	}

	//Check if javascript redirects user
	if(isset($_GET["username"])){
		try {
			$auth_data = checkTelegramAuthorization($_GET);
			echo "<pre>";
			print_r($auth_data);
		}catch (Exception $e) {
			die ($e->getMessage());
		}
	}
?>