on:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
    build:
      name: Run Script
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Script
          run: ./getdmr_id.ps1
          shell: pwsh