name: Download DMR ID
on: 
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    name: Run Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Amadevus/pwsh-script@v2
        id: script
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          script: |
            $dmridCSVFile = "./DMRid/dmrid.csv"
            $ipblacklistFile = "./ipblacklist.csv"
            $dmridDatFile = "./dmrid.dat"
            $DMRIdsFile = "./DMRIds.dat"

            Write-Output "--> Download dmrid from GD..."
            invoke-webrequest `
              -Uri "https://docs.google.com/spreadsheets/d/1dJBa8J5iXUmXk6cKkXX5w6N43xu8uEkvXUOZkozs9Es/gviz/tq?tqx=out:csv&sheet=Sheet1" `
              -OutFile $dmridCSVFile
            Write-Output "------------"

            Write-Output "--> Replace dmrid.dat..."
            $dmridCSVcontent = $((Get-Content $dmridCSVFile).Replace('"','') -match '^([0-9]{7}\,\w+\,)(.*)$' | Where-Object { $_ -ne "" }).ToUpper() | Sort-Object -Unique
            
            $dmridCSVcontent.Replace(",",";") -replace '^([0-9]{7}\;\w+\;)(.*)$','$1' | Set-Content $dmridDatFile -Force
            Write-Output "------------"

            Write-Output "--> Replace DMRIds.dat..."
            $DMRIds = $dmridCSVcontent -replace '^([0-9]{7}\,\w+\,)(.*)$','$1'
            $DMRIds2 = $DMRIds -replace ",$",""
            $DMRIdsClean = $DMRIds2 -replace ",","`t"
            $DMRIdsClean | Where-Object { $_ -ne "" } | Sort-Object -Unique | Set-Content $DMRIdsFile -Force
            Write-Output "------------"

            Write-Output "Done..!"

      - name: Update files in repository
        uses: actions-x/commit@v6
        with:
          email: "krot4u@gmail.com"
          name: GitHub Actions Autocommitter
          branch: master
          files: dmrid.dat DMRIds.dat ipblacklist.csv
          repository: https://github.com/${{ github.repository }}
          token: ${{ github.token }}
          force: true
          #directory: path/to/different/repo

      # - name: Push DMRIds.dat to Public
      #   uses: dmnemec/copy_file_to_another_repo_action@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.GIT_TOKEN }}
      #   with:
      #     source_file: 'DMRIds.dat'
      #     destination_repo: 'krot4u/Public_scripts'
      #     destination_branch: 'master'
      #     user_email: 'krot4u@gmail.com'
      #     user_name: 'krot4u'
      #     commit_message: 'Commit DMRIDs.dat'
