name: Download DMR ID
on: 
  workflow_dispatch:
  # schedule:
  #   - cron: "0 5 */30 * *"

jobs:
  build:
    name: Run Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - name: Script
      #   run: ./getdmr_id.ps1
      #   shell: pwsh

      - uses: Amadevus/pwsh-script@v2
        id: script
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          script: |
            $dmridCSVFile = "./DMRid/dmrid.csv"
            $blacklistCSVFile = "./DMRid/blacklist.csv"
            $dmridDatFile = "./dmrid.dat"
            $blacklistFile ="./xlxd.blacklist"
            $DMRIdsFile = "./DMRIds.dat"

            Write-Output "--> Download from Original DMRIds..."
            invoke-webrequest `
              -Uri "http://www.pistar.uk/downloads/DMRIds.dat" `
              -OutFile $DMRIdsFile
            Write-Output "------------"

            Write-Output "--> Download dmrid from GD..."
            invoke-webrequest `
              -Uri "https://docs.google.com/spreadsheets/d/1dJBa8J5iXUmXk6cKkXX5w6N43xu8uEkvXUOZkozs9Es/export?format=csv" `
              -OutFile $dmridCSVFile
            Write-Output "------------"

            Write-Output "--> Download blacklist from GD..."
            invoke-webrequest `
              -Uri "https://docs.google.com/spreadsheets/d/1dJBa8J5iXUmXk6cKkXX5w6N43xu8uEkvXUOZkozs9Es/gviz/tq?tqx=out:csv&sheet=blacklist" `
              -OutFile $blacklistCSVFile
            Write-Output "------------"

            Write-Output "--> Replace dmrid.dat..."
            $dmridCSVcontent = $(Get-Content $dmridCSVFile | Select-Object -Skip 1).ToUpper() | Sort-Object -Unique
            $dmridCSVcontent.Replace(",",";")-replace '$',';' | Set-Content $dmridDatFile -Force
            Write-Output "------------"

            Write-Output "--> Replace xlxd.blacklist"
            ((Get-Content $blacklistCSVFile | Select-Object -Skip 1).ToUpper() | Sort-Object -Unique).Replace('"','') | Set-Content $blacklistFile -Force
            Write-Output "------------"

            Write-Output "--> Replace DMRIds.dat..."
            $DMRIds = $dmridCSVcontent -replace ",","`t"
            $DMRIds -replace "$","`tRussia" | Add-Content $DMRIdsFile
            Write-Output "------------"

            #gh run download 4156043384 -n dmrid.dat -n DMRIds.dat

            Write-Output "Done..!"

      - name: Update files in repository
        run: |
          git config --global user.email "krot4u@gmail.com"
          git config --global user.name "krot4u"
          git add ./dmrid.dat ./DMRIds.dat ./xlxd.blacklist
          git commit -a -m 'Files Updated'
          git push

      # - name: Add files to Repo
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     default_author: github_actions
      #     message: 'dmrid.dat Files Updated'
      #     add: 'dmrid.dat'
      # - name: Add files to Repo
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     default_author: github_actions
      #     message: 'DMRIds.dat Files Updated'
      #     add: 'DMRIds.dat'
      # - name: Add files to Repo
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     default_author: github_actions
      #     message: 'DMRIds.dat Files Updated'
      #     add: 'xlxd.blacklist'