name: Download DMR ID
on: 
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    name: Run Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Amadevus/pwsh-script@v2
        id: script
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          script: |
            $dmridCSVFile = "./DMRid/dmrid.csv"
            $blacklistCSVFile = "./DMRid/blacklist.csv"
            $ipblacklistFile = "./ipblacklist.csv"
            $dmridDatFile = "./dmrid.dat"
            $blacklistFile ="./xlxd.blacklist"
            $DMRIdsFile = "./DMRIds.dat"

            Write-Output "--> Download from Original DMRIds..."
            invoke-webrequest `
              -Uri "http://www.pistar.uk/downloads/DMRIds.dat" `
              -OutFile $DMRIdsFile
            Write-Output "------------"

            Write-Output "--> Download dmrid from GD..."
            invoke-webrequest `
              -Uri "https://docs.google.com/spreadsheets/d/1dJBa8J5iXUmXk6cKkXX5w6N43xu8uEkvXUOZkozs9Es/export?format=csv" `
              -OutFile $dmridCSVFile
            Write-Output "------------"

            Write-Output "--> Download blacklist from GD..."
            invoke-webrequest `
              -Uri "https://docs.google.com/spreadsheets/d/1dJBa8J5iXUmXk6cKkXX5w6N43xu8uEkvXUOZkozs9Es/gviz/tq?tqx=out:csv&sheet=blacklist" `
              -OutFile $blacklistCSVFile
            Write-Output "------------"

            Write-Output "--> Download ipblacklist from GD..."
            invoke-webrequest `
              -Uri "https://docs.google.com/spreadsheets/d/1dJBa8J5iXUmXk6cKkXX5w6N43xu8uEkvXUOZkozs9Es/gviz/tq?tqx=out:csv&sheet=ipblacklist" `
              -OutFile $ipblacklistFile
            Write-Output "------------"

            Write-Output "--> Replace dmrid.dat..."
            $dmridCSVcontent = $(Get-Content $dmridCSVFile | Select-Object -Skip 1).ToUpper() | Sort-Object -Unique
            $dmridCSVcontent.Replace(",",";")-replace '$',';' | Set-Content $dmridDatFile -Force
            Write-Output "------------"

            Write-Output "--> Replace xlxd.blacklist"
            ((Get-Content $blacklistCSVFile | Select-Object -Skip 1).ToUpper() | Sort-Object -Unique).Replace('"','') | Set-Content $blacklistFile -Force
            Write-Output "------------"

            Write-Output "--> Replace DMRIds.dat..."
            $DMRIds = $dmridCSVcontent -replace ",","`t"
            $DMRIds -replace "$","`tRussia" | Add-Content $DMRIdsFile
            Write-Output "------------"

            Write-Output "Done..!"

      - name: Update files in repository
        uses: actions-x/commit@v6
        with:
          email: "krot4u@gmail.com"
          name: GitHub Actions Autocommitter
          branch: master
          files: dmrid.dat DMRIds.dat xlxd.blacklist ipblacklist.csv
          repository: https://github.com/${{ github.repository }}
          token: ${{ github.token }}
          force: true
          #directory: path/to/different/repo
